import Head from "next/head";
import { Box, Text } from "@chakra-ui/react";
import AreaChart2 from "@/components/AreaChart2";
import DonutChart from "@/components/DonutChart";
import BarChart from "@/components/BarChart";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box maxW={"7xl"} minH={"100vh"} mx="auto" p={{ base: 2, md: 8 }}>
          <Text>Hello World</Text>
          <AreaChart2 />
          <Box maxW={720} my={10}>
            <DonutChart />
          </Box>
          <BarChart />
        </Box>
      </main>
    </>
  );
}
